emcc -O0 -I utilities -I linear-algebra/kernels/2mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/2mm/2mm.c -DPOLYBENCH_TIME -o emcc/2mm_time_00.html
emcc -O0 -I utilities -I linear-algebra/kernels/3mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/3mm/3mm.c -DPOLYBENCH_TIME -o emcc/3mm_time_00.html
emcc -O0 -I utilities -I linear-algebra/kernels/atax/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/atax/atax.c -DPOLYBENCH_TIME -o emcc/atax_time_00.html
emcc -O0 -I utilities -I linear-algebra/kernels/bicg/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/bicg/bicg.c -DPOLYBENCH_TIME -o emcc/bicg_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/cholesky/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/cholesky/cholesky.c -DPOLYBENCH_TIME -o emcc/cholesky_time_00.html
emcc -O0 -I utilities -I linear-algebra/kernels/doitgen/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/doitgen/doitgen.c -DPOLYBENCH_TIME -o emcc/doitgen_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/gemm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemm/gemm.c -DPOLYBENCH_TIME -o emcc/gemm_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/gemver/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemver/gemver.c -DPOLYBENCH_TIME -o emcc/gemver_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/gesummv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gesummv/gesummv.c -DPOLYBENCH_TIME -o emcc/gesummv_time_00.html
emcc -O0 -I utilities -I linear-algebra/kernels/mvt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/mvt/mvt.c -DPOLYBENCH_TIME -o emcc/mvt_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/symm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/symm/symm.c -DPOLYBENCH_TIME -o emcc/symm_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/syr2k/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syr2k/syr2k.c -DPOLYBENCH_TIME -o emcc/syr2k_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/syrk/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syrk/syrk.c -DPOLYBENCH_TIME -o emcc/syrk_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/trisolv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/trisolv/trisolv.c -DPOLYBENCH_TIME -o emcc/trisolv_time_00.html
emcc -O0 -I utilities -I linear-algebra/blas/trmm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/trmm/trmm.c -DPOLYBENCH_TIME -o emcc/trmm_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/durbin/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/durbin/durbin.c -DPOLYBENCH_TIME -o emcc/durbin_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/gramschmidt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/gramschmidt/gramschmidt.c -DPOLYBENCH_TIME -o emcc/gramschmidt_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/lu/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/lu/lu.c -DPOLYBENCH_TIME -o emcc/lu_time_00.html
emcc -O0 -I utilities -I linear-algebra/solvers/ludcmp/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/ludcmp/ludcmp.c -DPOLYBENCH_TIME -o emcc/ludcmp_time_00.html
emcc -O0 -I utilities -I datamining/correlation/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/correlation/correlation.c -DPOLYBENCH_TIME -o emcc/correlation_time_00.html
emcc -O0 -I utilities -I datamining/covariance/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/covariance/covariance.c -DPOLYBENCH_TIME -o emcc/covariance_time_00.html
emcc -O0 -I utilities -I medley/floyd-warshall/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/floyd-warshall/floyd-warshall.c -DPOLYBENCH_TIME -o emcc/floyd-warshall_time_00.html
emcc -O0 -I utilities -I medley/nussinov/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/nussinov/nussinov.c -DPOLYBENCH_TIME -o emcc/nussinov_time_00.html
emcc -O0 -I utilities -I medley/deriche/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/deriche/deriche.c -DPOLYBENCH_TIME -o emcc/deriche_time_00.html
emcc -O0 -I utilities -I stencils/adi/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/adi/adi.c -DPOLYBENCH_TIME -o emcc/adi_time_00.html
emcc -O0 -I utilities -I stencils/fdtd-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/fdtd-2d/fdtd-2d.c -DPOLYBENCH_TIME -o emcc/fdtd-2d_time_00.html
emcc -O0 -I utilities -I stencils/jacobi-1d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-1d/jacobi-1d.c -DPOLYBENCH_TIME -o emcc/jacobi-1d_time_00.html
emcc -O0 -I utilities -I stencils/jacobi-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-2d/jacobi-2d.c -DPOLYBENCH_TIME -o emcc/jacobi-2d_time_00.html
emcc -O0 -I utilities -I stencils/seidel-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/seidel-2d/seidel-2d.c -DPOLYBENCH_TIME -o emcc/seidel-2d_time_00.html
emcc -O0 -I utilities -I stencils/heat-3d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/heat-3d/heat-3d.c -DPOLYBENCH_TIME -o emcc/heat-3d_time_00.html

emcc -O1 -I utilities -I linear-algebra/kernels/2mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/2mm/2mm.c -DPOLYBENCH_TIME -o emcc/2mm_time_01.html
emcc -O1 -I utilities -I linear-algebra/kernels/3mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/3mm/3mm.c -DPOLYBENCH_TIME -o emcc/3mm_time_01.html
emcc -O1 -I utilities -I linear-algebra/kernels/atax/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/atax/atax.c -DPOLYBENCH_TIME -o emcc/atax_time_01.html
emcc -O1 -I utilities -I linear-algebra/kernels/bicg/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/bicg/bicg.c -DPOLYBENCH_TIME -o emcc/bicg_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/cholesky/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/cholesky/cholesky.c -DPOLYBENCH_TIME -o emcc/cholesky_time_01.html
emcc -O1 -I utilities -I linear-algebra/kernels/doitgen/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/doitgen/doitgen.c -DPOLYBENCH_TIME -o emcc/doitgen_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/gemm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemm/gemm.c -DPOLYBENCH_TIME -o emcc/gemm_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/gemver/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemver/gemver.c -DPOLYBENCH_TIME -o emcc/gemver_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/gesummv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gesummv/gesummv.c -DPOLYBENCH_TIME -o emcc/gesummv_time_01.html
emcc -O1 -I utilities -I linear-algebra/kernels/mvt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/mvt/mvt.c -DPOLYBENCH_TIME -o emcc/mvt_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/symm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/symm/symm.c -DPOLYBENCH_TIME -o emcc/symm_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/syr2k/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syr2k/syr2k.c -DPOLYBENCH_TIME -o emcc/syr2k_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/syrk/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syrk/syrk.c -DPOLYBENCH_TIME -o emcc/syrk_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/trisolv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/trisolv/trisolv.c -DPOLYBENCH_TIME -o emcc/trisolv_time_01.html
emcc -O1 -I utilities -I linear-algebra/blas/trmm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/trmm/trmm.c -DPOLYBENCH_TIME -o emcc/trmm_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/durbin/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/durbin/durbin.c -DPOLYBENCH_TIME -o emcc/durbin_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/gramschmidt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/gramschmidt/gramschmidt.c -DPOLYBENCH_TIME -o emcc/gramschmidt_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/lu/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/lu/lu.c -DPOLYBENCH_TIME -o emcc/lu_time_01.html
emcc -O1 -I utilities -I linear-algebra/solvers/ludcmp/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/ludcmp/ludcmp.c -DPOLYBENCH_TIME -o emcc/ludcmp_time_01.html
emcc -O1 -I utilities -I datamining/correlation/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/correlation/correlation.c -DPOLYBENCH_TIME -o emcc/correlation_time_01.html
emcc -O1 -I utilities -I datamining/covariance/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/covariance/covariance.c -DPOLYBENCH_TIME -o emcc/covariance_time_01.html
emcc -O1 -I utilities -I medley/floyd-warshall/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/floyd-warshall/floyd-warshall.c -DPOLYBENCH_TIME -o emcc/floyd-warshall_time_01.html
emcc -O1 -I utilities -I medley/nussinov/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/nussinov/nussinov.c -DPOLYBENCH_TIME -o emcc/nussinov_time_01.html
emcc -O1 -I utilities -I medley/deriche/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/deriche/deriche.c -DPOLYBENCH_TIME -o emcc/deriche_time_01.html
emcc -O1 -I utilities -I stencils/adi/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/adi/adi.c -DPOLYBENCH_TIME -o emcc/adi_time_01.html
emcc -O1 -I utilities -I stencils/fdtd-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/fdtd-2d/fdtd-2d.c -DPOLYBENCH_TIME -o emcc/fdtd-2d_time_01.html
emcc -O1 -I utilities -I stencils/jacobi-1d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-1d/jacobi-1d.c -DPOLYBENCH_TIME -o emcc/jacobi-1d_time_01.html
emcc -O1 -I utilities -I stencils/jacobi-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-2d/jacobi-2d.c -DPOLYBENCH_TIME -o emcc/jacobi-2d_time_01.html
emcc -O1 -I utilities -I stencils/seidel-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/seidel-2d/seidel-2d.c -DPOLYBENCH_TIME -o emcc/seidel-2d_time_01.html
emcc -O1 -I utilities -I stencils/heat-3d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/heat-3d/heat-3d.c -DPOLYBENCH_TIME -o emcc/heat-3d_time_01.html

emcc -O2 -I utilities -I linear-algebra/kernels/2mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/2mm/2mm.c -DPOLYBENCH_TIME -o emcc/2mm_time_02.html
emcc -O2 -I utilities -I linear-algebra/kernels/3mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/3mm/3mm.c -DPOLYBENCH_TIME -o emcc/3mm_time_02.html
emcc -O2 -I utilities -I linear-algebra/kernels/atax/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/atax/atax.c -DPOLYBENCH_TIME -o emcc/atax_time_02.html
emcc -O2 -I utilities -I linear-algebra/kernels/bicg/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/bicg/bicg.c -DPOLYBENCH_TIME -o emcc/bicg_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/cholesky/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/cholesky/cholesky.c -DPOLYBENCH_TIME -o emcc/cholesky_time_02.html
emcc -O2 -I utilities -I linear-algebra/kernels/doitgen/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/doitgen/doitgen.c -DPOLYBENCH_TIME -o emcc/doitgen_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/gemm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemm/gemm.c -DPOLYBENCH_TIME -o emcc/gemm_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/gemver/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemver/gemver.c -DPOLYBENCH_TIME -o emcc/gemver_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/gesummv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gesummv/gesummv.c -DPOLYBENCH_TIME -o emcc/gesummv_time_02.html
emcc -O2 -I utilities -I linear-algebra/kernels/mvt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/mvt/mvt.c -DPOLYBENCH_TIME -o emcc/mvt_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/symm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/symm/symm.c -DPOLYBENCH_TIME -o emcc/symm_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/syr2k/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syr2k/syr2k.c -DPOLYBENCH_TIME -o emcc/syr2k_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/syrk/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syrk/syrk.c -DPOLYBENCH_TIME -o emcc/syrk_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/trisolv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/trisolv/trisolv.c -DPOLYBENCH_TIME -o emcc/trisolv_time_02.html
emcc -O2 -I utilities -I linear-algebra/blas/trmm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/trmm/trmm.c -DPOLYBENCH_TIME -o emcc/trmm_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/durbin/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/durbin/durbin.c -DPOLYBENCH_TIME -o emcc/durbin_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/gramschmidt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/gramschmidt/gramschmidt.c -DPOLYBENCH_TIME -o emcc/gramschmidt_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/lu/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/lu/lu.c -DPOLYBENCH_TIME -o emcc/lu_time_02.html
emcc -O2 -I utilities -I linear-algebra/solvers/ludcmp/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/ludcmp/ludcmp.c -DPOLYBENCH_TIME -o emcc/ludcmp_time_02.html
emcc -O2 -I utilities -I datamining/correlation/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/correlation/correlation.c -DPOLYBENCH_TIME -o emcc/correlation_time_02.html
emcc -O2 -I utilities -I datamining/covariance/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/covariance/covariance.c -DPOLYBENCH_TIME -o emcc/covariance_time_02.html
emcc -O2 -I utilities -I medley/floyd-warshall/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/floyd-warshall/floyd-warshall.c -DPOLYBENCH_TIME -o emcc/floyd-warshall_time_02.html
emcc -O2 -I utilities -I medley/nussinov/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/nussinov/nussinov.c -DPOLYBENCH_TIME -o emcc/nussinov_time_02.html
emcc -O2 -I utilities -I medley/deriche/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/deriche/deriche.c -DPOLYBENCH_TIME -o emcc/deriche_time_02.html
emcc -O2 -I utilities -I stencils/adi/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/adi/adi.c -DPOLYBENCH_TIME -o emcc/adi_time_02.html
emcc -O2 -I utilities -I stencils/fdtd-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/fdtd-2d/fdtd-2d.c -DPOLYBENCH_TIME -o emcc/fdtd-2d_time_02.html
emcc -O2 -I utilities -I stencils/jacobi-1d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-1d/jacobi-1d.c -DPOLYBENCH_TIME -o emcc/jacobi-1d_time_02.html
emcc -O2 -I utilities -I stencils/jacobi-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-2d/jacobi-2d.c -DPOLYBENCH_TIME -o emcc/jacobi-2d_time_02.html
emcc -O2 -I utilities -I stencils/seidel-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/seidel-2d/seidel-2d.c -DPOLYBENCH_TIME -o emcc/seidel-2d_time_02.html
emcc -O2 -I utilities -I stencils/heat-3d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/heat-3d/heat-3d.c -DPOLYBENCH_TIME -o emcc/heat-3d_time_02.html

emcc -O3 -I utilities -I linear-algebra/kernels/2mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/2mm/2mm.c -DPOLYBENCH_TIME -o emcc/2mm_time_03.html
emcc -O3 -I utilities -I linear-algebra/kernels/3mm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/3mm/3mm.c -DPOLYBENCH_TIME -o emcc/3mm_time_03.html
emcc -O3 -I utilities -I linear-algebra/kernels/atax/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/atax/atax.c -DPOLYBENCH_TIME -o emcc/atax_time_03.html
emcc -O3 -I utilities -I linear-algebra/kernels/bicg/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/bicg/bicg.c -DPOLYBENCH_TIME -o emcc/bicg_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/cholesky/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/cholesky/cholesky.c -DPOLYBENCH_TIME -o emcc/cholesky_time_03.html
emcc -O3 -I utilities -I linear-algebra/kernels/doitgen/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/doitgen/doitgen.c -DPOLYBENCH_TIME -o emcc/doitgen_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/gemm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemm/gemm.c -DPOLYBENCH_TIME -o emcc/gemm_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/gemver/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gemver/gemver.c -DPOLYBENCH_TIME -o emcc/gemver_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/gesummv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/gesummv/gesummv.c -DPOLYBENCH_TIME -o emcc/gesummv_time_03.html
emcc -O3 -I utilities -I linear-algebra/kernels/mvt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/kernels/mvt/mvt.c -DPOLYBENCH_TIME -o emcc/mvt_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/symm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/symm/symm.c -DPOLYBENCH_TIME -o emcc/symm_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/syr2k/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syr2k/syr2k.c -DPOLYBENCH_TIME -o emcc/syr2k_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/syrk/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/syrk/syrk.c -DPOLYBENCH_TIME -o emcc/syrk_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/trisolv/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/trisolv/trisolv.c -DPOLYBENCH_TIME -o emcc/trisolv_time_03.html
emcc -O3 -I utilities -I linear-algebra/blas/trmm/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/blas/trmm/trmm.c -DPOLYBENCH_TIME -o emcc/trmm_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/durbin/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/durbin/durbin.c -DPOLYBENCH_TIME -o emcc/durbin_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/gramschmidt/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/gramschmidt/gramschmidt.c -DPOLYBENCH_TIME -o emcc/gramschmidt_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/lu/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/lu/lu.c -DPOLYBENCH_TIME -o emcc/lu_time_03.html
emcc -O3 -I utilities -I linear-algebra/solvers/ludcmp/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun linear-algebra/solvers/ludcmp/ludcmp.c -DPOLYBENCH_TIME -o emcc/ludcmp_time_03.html
emcc -O3 -I utilities -I datamining/correlation/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/correlation/correlation.c -DPOLYBENCH_TIME -o emcc/correlation_time_03.html
emcc -O3 -I utilities -I datamining/covariance/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun datamining/covariance/covariance.c -DPOLYBENCH_TIME -o emcc/covariance_time_03.html
emcc -O3 -I utilities -I medley/floyd-warshall/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/floyd-warshall/floyd-warshall.c -DPOLYBENCH_TIME -o emcc/floyd-warshall_time_03.html
emcc -O3 -I utilities -I medley/nussinov/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/nussinov/nussinov.c -DPOLYBENCH_TIME -o emcc/nussinov_time_03.html
emcc -O3 -I utilities -I medley/deriche/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun medley/deriche/deriche.c -DPOLYBENCH_TIME -o emcc/deriche_time_03.html
emcc -O3 -I utilities -I stencils/adi/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/adi/adi.c -DPOLYBENCH_TIME -o emcc/adi_time_03.html
emcc -O3 -I utilities -I stencils/fdtd-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/fdtd-2d/fdtd-2d.c -DPOLYBENCH_TIME -o emcc/fdtd-2d_time_03.html
emcc -O3 -I utilities -I stencils/jacobi-1d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-1d/jacobi-1d.c -DPOLYBENCH_TIME -o emcc/jacobi-1d_time_03.html
emcc -O3 -I utilities -I stencils/jacobi-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/jacobi-2d/jacobi-2d.c -DPOLYBENCH_TIME -o emcc/jacobi-2d_time_03.html
emcc -O3 -I utilities -I stencils/seidel-2d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/seidel-2d/seidel-2d.c -DPOLYBENCH_TIME -o emcc/seidel-2d_time_03.html
emcc -O3 -I utilities -I stencils/heat-3d/ utilities/polybench.c -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --emrun stencils/heat-3d/heat-3d.c -DPOLYBENCH_TIME -o emcc/heat-3d_time_03.html